// Package workers contains long-running background processes for Lumina-Core.
// Workers are designed to run as goroutines started during server startup and
// cancelled cleanly via context on graceful shutdown.
package workers

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"math/big"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/devwrightlabs/plu-lumina/backend/internal/models"
	"github.com/devwrightlabs/plu-lumina/backend/internal/services"
)

// ─── Environment variable names ───────────────────────────────────────────────

const (
	// EnvEVMRPCURL is the JSON-RPC endpoint for the monitored EVM chain.
	// Example: https://mainnet.infura.io/v3/<PROJECT_ID>
	EnvEVMRPCURL = "EVM_RPC_URL"

	// EnvEVMMinConfirmations is the number of block confirmations required
	// before a detected transfer advances to confirmed status.  Defaults to
	// evmDefaultMinConfirmations when unset.
	EnvEVMMinConfirmations = "EVM_MIN_CONFIRMATIONS"
)

// ─── Timing & safety constants ────────────────────────────────────────────────

const (
	// omnichainPollInterval is the normal cadence between reconciliation cycles.
	omnichainPollInterval = 15 * time.Second

	// omnichainMinBackoff is the initial back-off after the first error.
	omnichainMinBackoff = 5 * time.Second

	// omnichainMaxBackoff caps back-off so a prolonged RPC outage does not
	// hold the goroutine indefinitely.
	omnichainMaxBackoff = 5 * time.Minute

	// evmRequestTimeout is the per-call deadline for EVM RPC requests.
	evmRequestTimeout = 10 * time.Second

	// evmDefaultMinConfirmations is the reorg-safe confirmation threshold used
	// when EVM_MIN_CONFIRMATIONS is not set.  12 blocks (≈ 3 min on Ethereum
	// mainnet) is the industry-standard minimum for ERC-20 deposits.
	evmDefaultMinConfirmations = 12

	// erc20TransferTopicHex is the keccak-256 topic for the ERC-20 Transfer
	// event: Transfer(address indexed from, address indexed to, uint256 value)
	// This is a well-known constant; see EIP-20.
	erc20TransferTopicHex = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
)

// ─── EVM JSON-RPC types ───────────────────────────────────────────────────────

// evmRPCRequest is a JSON-RPC 2.0 request body.
type evmRPCRequest struct {
	JSONRPC string        `json:"jsonrpc"`
	Method  string        `json:"method"`
	Params  []interface{} `json:"params"`
	ID      int           `json:"id"`
}

// evmRPCResponse is the minimal JSON-RPC 2.0 response envelope.
type evmRPCResponse struct {
	Result json.RawMessage `json:"result"`
	Error  *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// evmLog represents a single entry from eth_getLogs.
type evmLog struct {
	// TransactionHash is the hash of the transaction that emitted this log.
	TransactionHash string `json:"transactionHash"`
	// BlockNumber is the hex-encoded block number where the log was emitted.
	BlockNumber string `json:"blockNumber"`
	// Topics are the indexed log topics; Topics[0] is the event signature.
	Topics []string `json:"topics"`
	// Data is the ABI-encoded non-indexed log data (hex string).
	Data string `json:"data"`
	// Address is the contract address that emitted the log.
	Address string `json:"address"`
	// Removed is true when the log was removed due to a chain re-organisation.
	// Any deposit flagged as removed must be re-evaluated.
	Removed bool `json:"removed"`
}

// ─── OmnichainListenerConfig ──────────────────────────────────────────────────

// OmnichainListenerConfig holds the configuration for OmnichainListener
// construction.
type OmnichainListenerConfig struct {
	// EVMRPCURL is the EVM JSON-RPC endpoint. Required.
	EVMRPCURL string

	// MinConfirmations is the reorg-safe block depth required before a
	// detected transfer is advanced to confirmed status.
	MinConfirmations int

	// PollInterval overrides the reconciliation cadence.  Defaults to
	// omnichainPollInterval when zero.
	PollInterval time.Duration
}

// ─── OmnichainListener ────────────────────────────────────────────────────────

// OmnichainListener is the Phase 13 background worker that monitors EVM-
// compatible chains for incoming transfers to one-time deposit addresses
// generated by the Lumina backend.
//
// Resilience strategy:
//  1. Each reconciliation cycle runs under a bounded context; a hung RPC
//     call cannot block the ticker loop indefinitely.
//  2. Transient RPC errors trigger exponential back-off up to omnichainMaxBackoff.
//  3. Per-deposit errors are logged without aborting the rest of the cycle.
//  4. Chain re-organisations are detected via the evmLog.Removed flag and by
//     requiring MinConfirmations blocks above the detection block before
//     advancing the deposit status — preventing a re-org from double-minting.
//  5. Once a deposit reaches DepositStatusMinting or higher it is never
//     re-processed, providing idempotent minting semantics.
type OmnichainListener struct {
	store            *services.DepositStore
	minter           *services.OmnichainMinter
	evmRPCURL        string
	minConfirmations int
	pollInterval     time.Duration
	httpClient       *http.Client
}

// NewOmnichainListener constructs an OmnichainListener from explicit config.
func NewOmnichainListener(
	store *services.DepositStore,
	minter *services.OmnichainMinter,
	cfg OmnichainListenerConfig,
) (*OmnichainListener, error) {
	if store == nil {
		return nil, fmt.Errorf("deposit store must not be nil")
	}
	if minter == nil {
		return nil, fmt.Errorf("omnichain minter must not be nil")
	}
	if cfg.EVMRPCURL == "" {
		return nil, fmt.Errorf("OmnichainListenerConfig.EVMRPCURL is required")
	}

	minConf := cfg.MinConfirmations
	if minConf <= 0 {
		minConf = evmDefaultMinConfirmations
	}

	interval := cfg.PollInterval
	if interval <= 0 {
		interval = omnichainPollInterval
	}

	return &OmnichainListener{
		store:            store,
		minter:           minter,
		evmRPCURL:        cfg.EVMRPCURL,
		minConfirmations: minConf,
		pollInterval:     interval,
		httpClient: &http.Client{
			Timeout:   evmRequestTimeout,
			Transport: http.DefaultTransport,
		},
	}, nil
}

// NewOmnichainListenerFromEnv is a convenience constructor that reads
// EVM_RPC_URL and EVM_MIN_CONFIRMATIONS from the process environment.
func NewOmnichainListenerFromEnv(
	store *services.DepositStore,
	minter *services.OmnichainMinter,
) (*OmnichainListener, error) {
	rpcURL := os.Getenv(EnvEVMRPCURL)
	if rpcURL == "" {
		return nil, fmt.Errorf("%s environment variable is required", EnvEVMRPCURL)
	}

	minConf := evmDefaultMinConfirmations
	if v := os.Getenv(EnvEVMMinConfirmations); v != "" {
		parsed, err := strconv.Atoi(v)
		if err != nil || parsed <= 0 {
			return nil, fmt.Errorf("invalid %s value %q: must be a positive integer", EnvEVMMinConfirmations, v)
		}
		minConf = parsed
	}

	return NewOmnichainListener(store, minter, OmnichainListenerConfig{
		EVMRPCURL:        rpcURL,
		MinConfirmations: minConf,
	})
}

// ─── Run ──────────────────────────────────────────────────────────────────────

// MinConfirmations returns the reorg-safe block depth configured on this
// listener.  main.go passes this value to handlers.InitDepositStore so the
// HTTP handler can include it in DepositAddressResponse, keeping the UI
// synchronised with the backend's actual confirmation requirement.
func (l *OmnichainListener) MinConfirmations() int {
	return l.minConfirmations
}

// Run starts the omnichain listener loop and blocks until ctx is cancelled.
// It must be invoked in a dedicated goroutine:
//
//	listenerCtx, cancel := context.WithCancel(context.Background())
//	defer cancel()
//	go omnichainListener.Run(listenerCtx)
func (l *OmnichainListener) Run(ctx context.Context) {
	log.Printf(
		"[omnichain-listener] started (rpc=%s min_confirmations=%d poll=%s)",
		l.evmRPCURL, l.minConfirmations, l.pollInterval,
	)

	ticker := time.NewTicker(l.pollInterval)
	defer ticker.Stop()

	currentBackoff := time.Duration(0)

	for {
		select {
		case <-ctx.Done():
			log.Println("[omnichain-listener] context cancelled; stopping")
			return

		case <-ticker.C:
			// Each cycle runs under its own bounded context so a slow RPC
			// call cannot hold the ticker goroutine past the next interval.
			cycleCtx, cycleCancel := context.WithTimeout(ctx, l.pollInterval)
			err := l.reconcile(cycleCtx)
			cycleCancel()

			if err != nil {
				currentBackoff = omnichainNextBackoff(currentBackoff)
				log.Printf("[omnichain-listener] cycle error (backoff %s): %v",
					currentBackoff, err)
				ticker.Reset(currentBackoff)
			} else {
				if currentBackoff > 0 {
					log.Println("[omnichain-listener] EVM RPC recovered; resuming normal poll cadence")
				}
				currentBackoff = 0
				ticker.Reset(l.pollInterval)
			}
		}
	}
}

// ─── Reconciliation ───────────────────────────────────────────────────────────

// reconcile performs one full reconciliation cycle:
//  1. Expire stale pending deposits whose TTL has elapsed.
//  2. Fetch the current EVM block number.
//  3. For each active (pending / detected) deposit, scan for incoming
//     ERC-20 Transfer events or native ETH transfers.
//  4. For deposits with enough confirmations, trigger the Soroban mint.
func (l *OmnichainListener) reconcile(ctx context.Context) error {
	// Clean up deposits whose address window has elapsed.
	if n := l.store.ExpireStale(); n > 0 {
		log.Printf("[omnichain-listener] expired %d stale deposit(s)", n)
	}

	// Obtain the current canonical head block.  This single call anchors all
	// confirmation calculations for the cycle, ensuring consistency.
	currentBlock, err := l.fetchCurrentBlock(ctx)
	if err != nil {
		return fmt.Errorf("fetching current EVM block: %w", err)
	}

	active := l.store.ListPending()
	if len(active) == 0 {
		return nil
	}

	log.Printf("[omnichain-listener] reconciling %d active deposit(s) (head=%d)",
		len(active), currentBlock)

	for _, deposit := range active {
		if err := l.reconcileDeposit(ctx, deposit, currentBlock); err != nil {
			// Per-deposit errors are logged without aborting the rest of the
			// cycle; one bad deposit must not stall all others.
			log.Printf("[omnichain-listener] error reconciling deposit=%s: %v",
				deposit.ID, err)
		}
	}

	return nil
}

// reconcileDeposit checks or advances a single deposit through its lifecycle.
func (l *OmnichainListener) reconcileDeposit(
	ctx context.Context,
	deposit *models.CrossChainDeposit,
	currentBlock int64,
) error {
	switch deposit.Status {
	case models.DepositStatusPending:
		// Scan for the first inbound transfer to this deposit address.
		return l.scanForDeposit(ctx, deposit, currentBlock)

	case models.DepositStatusDetected:
		// Transfer already found; check whether MinConfirmations has been
		// reached to guard against chain re-organisations.
		return l.checkConfirmations(ctx, deposit, currentBlock)

	default:
		// All other states (confirmed, minting, minted, failed, expired) are
		// terminal or handled elsewhere; nothing to do here.
		return nil
	}
}

// scanForDeposit calls eth_getLogs to look for ERC-20 Transfer events (or
// eth_getBalance for native ETH) directed at the deposit address.
// On detection the deposit is advanced to DepositStatusDetected.
func (l *OmnichainListener) scanForDeposit(
	ctx context.Context,
	deposit *models.CrossChainDeposit,
	currentBlock int64,
) error {
	// Determine the search window: scan from creation block to current head.
	// For a newly-created deposit we use "earliest" as a safe lower bound.
	fromBlock := "earliest"

	var txHash, amount string
	var detectedBlock int64

	if deposit.ContractAddress != "" {
		// ── ERC-20 token transfer ─────────────────────────────────────────────
		// eth_getLogs filters for Transfer(from, to, value) events where
		// the second indexed topic (to) matches our deposit address.
		logs, err := l.fetchERC20Logs(ctx, deposit.ContractAddress, deposit.DepositAddress, fromBlock)
		if err != nil {
			return fmt.Errorf("fetching ERC-20 logs for deposit=%s: %w", deposit.ID, err)
		}
		for _, evmlog := range logs {
			// Ignore logs removed by a chain re-organisation.
			if evmlog.Removed {
				continue
			}
			txHash = evmlog.TransactionHash
			amount = decodeERC20Amount(evmlog.Data)
			detectedBlock = hexToInt64(evmlog.BlockNumber)
			// First non-removed Transfer event wins.  If multiple transfers
			// arrive at the same address (e.g. a user sends twice), only the
			// first is tracked for minting.  Subsequent transfers remain at
			// the address and must be handled by the sweep service.  For a
			// full production deployment, consider accumulating all transfers
			// within the deposit window and minting the aggregate amount.
			break
		}
	} else {
		// ── Native ETH / BNB / MATIC balance check ────────────────────────────
		// For native assets we poll the current balance; a non-zero balance
		// implies an inbound deposit.  The tx hash is not directly available
		// via balance polling so we leave it empty; the actual amount is the
		// current balance.
		balance, err := l.fetchNativeBalance(ctx, deposit.DepositAddress)
		if err != nil {
			return fmt.Errorf("fetching native balance for deposit=%s: %w", deposit.ID, err)
		}
		if balance != "" && balance != "0x0" {
			// Non-zero balance detected; record it without an explicit tx hash.
			amount = hexToDecimalStr(balance)
			detectedBlock = currentBlock
			// txHash is left empty; in production, use eth_getTransactionsByAddress
			// or a block explorer API to retrieve the originating hash.
		}
	}

	if txHash == "" && amount == "" {
		// No transfer detected in this cycle.
		return nil
	}

	deposit.Status = models.DepositStatusDetected
	deposit.ExternalTxHash = txHash
	deposit.ActualAmount = amount
	deposit.DetectedBlock = detectedBlock
	deposit.Confirmations = int(currentBlock - detectedBlock)
	deposit.UpdatedAt = time.Now().UTC()

	if err := l.store.Update(deposit); err != nil {
		return fmt.Errorf("persisting detection for deposit=%s: %w", deposit.ID, err)
	}

	log.Printf("[omnichain-listener] deposit=%s detected (block=%d amount=%s tx=%s)",
		deposit.ID, detectedBlock, amount, txHash)
	return nil
}

// checkConfirmations counts confirmations above the detected block and, once
// the threshold is met, advances the deposit to confirmed and triggers minting.
func (l *OmnichainListener) checkConfirmations(
	ctx context.Context,
	deposit *models.CrossChainDeposit,
	currentBlock int64,
) error {
	confirmations := int(currentBlock - deposit.DetectedBlock)

	if confirmations < 0 {
		// DetectedBlock is ahead of currentBlock — indicates a chain re-org.
		// Reset to pending so the next cycle re-scans from scratch.
		log.Printf(
			"[omnichain-listener] reorg detected for deposit=%s (detected_block=%d current=%d); resetting",
			deposit.ID, deposit.DetectedBlock, currentBlock,
		)
		deposit.Status = models.DepositStatusPending
		deposit.ExternalTxHash = ""
		deposit.ActualAmount = ""
		deposit.DetectedBlock = 0
		deposit.Confirmations = 0
		deposit.UpdatedAt = time.Now().UTC()
		return l.store.Update(deposit)
	}

	deposit.Confirmations = confirmations
	deposit.UpdatedAt = time.Now().UTC()

	if confirmations < l.minConfirmations {
		// Still accumulating confirmations; update the count and continue.
		log.Printf("[omnichain-listener] deposit=%s confirmations=%d/%d; waiting",
			deposit.ID, confirmations, l.minConfirmations)
		return l.store.Update(deposit)
	}

	// Threshold reached — mark confirmed and trigger the Soroban mint.
	deposit.Status = models.DepositStatusConfirmed
	deposit.UpdatedAt = time.Now().UTC()
	if err := l.store.Update(deposit); err != nil {
		return fmt.Errorf("persisting confirmation for deposit=%s: %w", deposit.ID, err)
	}

	log.Printf("[omnichain-listener] deposit=%s confirmed (%d blocks); triggering mint",
		deposit.ID, confirmations)

	// MintWrapped advances deposit to minted (or failed) and persists.
	// Any error here is returned so the outer caller logs it; the deposit
	// will be re-evaluated on the next cycle.
	if err := l.minter.MintWrapped(ctx, deposit.ID); err != nil {
		return fmt.Errorf("minting for deposit=%s: %w", deposit.ID, err)
	}

	return nil
}

// ─── EVM JSON-RPC helpers ─────────────────────────────────────────────────────

// fetchCurrentBlock calls eth_blockNumber and returns the current chain head
// as a decimal int64.
func (l *OmnichainListener) fetchCurrentBlock(ctx context.Context) (int64, error) {
	var raw string
	if err := l.evmCall(ctx, "eth_blockNumber", []interface{}{}, &raw); err != nil {
		return 0, fmt.Errorf("eth_blockNumber: %w", err)
	}
	return hexToInt64(raw), nil
}

// fetchERC20Logs calls eth_getLogs filtering for ERC-20 Transfer events emitted
// by contractAddress where the recipient (topics[2]) matches depositAddress.
func (l *OmnichainListener) fetchERC20Logs(
	ctx context.Context,
	contractAddress, depositAddress, fromBlock string,
) ([]evmLog, error) {
	// Pad the deposit address to a 32-byte topic (left-zero-padded).
	paddedAddr := padAddressToTopic(depositAddress)

	params := []interface{}{
		map[string]interface{}{
			"fromBlock": fromBlock,
			"toBlock":   "latest",
			"address":   contractAddress,
			"topics": []interface{}{
				erc20TransferTopicHex, // topics[0]: Transfer event signature
				nil,                   // topics[1]: from — any sender
				paddedAddr,            // topics[2]: to   — must match deposit address
			},
		},
	}

	var logs []evmLog
	if err := l.evmCall(ctx, "eth_getLogs", params, &logs); err != nil {
		return nil, fmt.Errorf("eth_getLogs: %w", err)
	}
	return logs, nil
}

// fetchNativeBalance calls eth_getBalance for the given address at the latest
// block and returns the hex-encoded balance string.
func (l *OmnichainListener) fetchNativeBalance(ctx context.Context, address string) (string, error) {
	var balance string
	if err := l.evmCall(ctx, "eth_getBalance", []interface{}{address, "latest"}, &balance); err != nil {
		return "", fmt.Errorf("eth_getBalance: %w", err)
	}
	return balance, nil
}

// evmCall performs a single JSON-RPC 2.0 call and unmarshals the result into
// out (which must be a pointer).
func (l *OmnichainListener) evmCall(
	ctx context.Context,
	method string,
	params []interface{},
	out interface{},
) error {
	body, err := json.Marshal(evmRPCRequest{
		JSONRPC: "2.0",
		Method:  method,
		Params:  params,
		ID:      1,
	})
	if err != nil {
		return fmt.Errorf("marshalling RPC request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, l.evmRPCURL, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("building RPC HTTP request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := l.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("EVM RPC HTTP error: %w", err)
	}
	defer func() {
		_, _ = io.Copy(io.Discard, resp.Body)
		resp.Body.Close()
	}()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("EVM RPC returned HTTP %d", resp.StatusCode)
	}

	var rpcResp evmRPCResponse
	if err := json.NewDecoder(resp.Body).Decode(&rpcResp); err != nil {
		return fmt.Errorf("decoding RPC response: %w", err)
	}

	if rpcResp.Error != nil {
		return fmt.Errorf("EVM RPC error %d: %s", rpcResp.Error.Code, rpcResp.Error.Message)
	}

	if err := json.Unmarshal(rpcResp.Result, out); err != nil {
		return fmt.Errorf("unmarshalling RPC result: %w", err)
	}
	return nil
}

// ─── Encoding helpers ─────────────────────────────────────────────────────────

// padAddressToTopic left-pads a 20-byte Ethereum address to a 32-byte log
// topic, as required by the ERC-20 Transfer indexed parameter encoding.
func padAddressToTopic(addr string) string {
	addr = strings.ToLower(strings.TrimPrefix(addr, "0x"))
	return "0x" + strings.Repeat("0", 64-len(addr)) + addr
}

// hexToInt64 converts a 0x-prefixed hex string to int64.
// Returns 0 on any parse error.
func hexToInt64(hex string) int64 {
	hex = strings.TrimPrefix(hex, "0x")
	n, err := strconv.ParseInt(hex, 16, 64)
	if err != nil {
		return 0
	}
	return n
}

// decodeERC20Amount converts the ABI-encoded non-indexed `value` field of an
// ERC-20 Transfer event into a decimal string.  The data field is a 32-byte
// big-endian integer encoded as a 0x-prefixed hex string.
func decodeERC20Amount(data string) string {
	data = strings.TrimPrefix(data, "0x")
	if len(data) == 0 {
		return "0"
	}
	b, ok := new(big.Int).SetString(data, 16)
	if !ok {
		return "0"
	}
	return b.String()
}

// hexToDecimalStr converts a hex-encoded integer (e.g. from eth_getBalance)
// to its decimal string representation.
func hexToDecimalStr(hex string) string {
	hex = strings.TrimPrefix(hex, "0x")
	if hex == "" {
		return "0"
	}
	b, ok := new(big.Int).SetString(hex, 16)
	if !ok {
		return "0"
	}
	return b.String()
}

// ─── Back-off helper ──────────────────────────────────────────────────────────

// omnichainNextBackoff computes the next exponential back-off duration,
// capped at omnichainMaxBackoff.
func omnichainNextBackoff(current time.Duration) time.Duration {
	if current <= 0 {
		return omnichainMinBackoff
	}
	next := current * 2
	if next > omnichainMaxBackoff {
		return omnichainMaxBackoff
	}
	return next
}
